#!/usr/bin/env sh
set -e
TOR_CONTROL_PASSWORD_HASH=`tor --quiet --hash-password ${TOR_CONTROL_PASSWORD}`
echo "SOCKSPort 9050" >> /etc/tor/torrc
echo "ControlPort 9051" >> /etc/tor/torrc
echo "HashedControlPassword ${TOR_CONTROL_PASSWORD_HASH}" >> /etc/tor/torrc
